# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setSizeIncrement(QtCore.QSize(1, 0))
        self.imgFrame = QtWidgets.QFrame(mainWindow)
        self.imgFrame.setGeometry(QtCore.QRect(20, 20, 381, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgFrame.sizePolicy().hasHeightForWidth())
        self.imgFrame.setSizePolicy(sizePolicy)
        self.imgFrame.setSizeIncrement(QtCore.QSize(10, 10))
        self.imgFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgFrame.setObjectName("imgFrame")
        self.imgHolder = QtWidgets.QGraphicsView(self.imgFrame)
        self.imgHolder.setGeometry(QtCore.QRect(0, 0, 381, 561))
        self.imgHolder.setObjectName("imgHolder")
        self.textFrame = QtWidgets.QScrollArea(mainWindow)
        self.textFrame.setGeometry(QtCore.QRect(420, 300, 361, 281))
        self.textFrame.setSizeIncrement(QtCore.QSize(10, 10))
        self.textFrame.setWidgetResizable(True)
        self.textFrame.setObjectName("textFrame")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 279))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textHolder = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textHolder.setGeometry(QtCore.QRect(0, 0, 361, 281))
        self.textHolder.setObjectName("textHolder")
        self.textFrame.setWidget(self.scrollAreaWidgetContents)
        self.btnFrame = QtWidgets.QFrame(mainWindow)
        self.btnFrame.setGeometry(QtCore.QRect(420, 90, 361, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrame.sizePolicy().hasHeightForWidth())
        self.btnFrame.setSizePolicy(sizePolicy)
        self.btnFrame.setSizeIncrement(QtCore.QSize(10, 10))
        self.btnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.analyzeBtn = QtWidgets.QPushButton(self.btnFrame)
        self.analyzeBtn.setGeometry(QtCore.QRect(0, 160, 361, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzeBtn.sizePolicy().hasHeightForWidth())
        self.analyzeBtn.setSizePolicy(sizePolicy)
        self.analyzeBtn.setObjectName("analyzeBtn")
        self.downloadBtn = QtWidgets.QPushButton(self.btnFrame)
        self.downloadBtn.setGeometry(QtCore.QRect(0, 107, 361, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadBtn.sizePolicy().hasHeightForWidth())
        self.downloadBtn.setSizePolicy(sizePolicy)
        self.downloadBtn.setObjectName("downloadBtn")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Lungo-Vision"))
        self.analyzeBtn.setText(_translate("mainWindow", "Анализировать"))
        self.downloadBtn.setText(_translate("mainWindow", "Загрузить снимок"))
